# Generated by Django 4.0.4 on 2022-05-06 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderprod',
            unique_together={('order_id', 'product_id')},
        ),
    ]
