# Generated by Django 4.0.4 on 2022-05-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0002_alter_orderprod_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(default='-'),
        ),
    ]
