# Generated by Django 4.0.3 on 2022-05-23 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0004_alter_cart_product_id_alter_cart_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdImage',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ecomm.product')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
