# Generated by Django 4.0.3 on 2022-05-24 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0006_alter_prodimage_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
