# Generated by Django 4.0.3 on 2022-05-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0007_remove_order_delivery_status_remove_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
