# Generated by Django 4.0.3 on 2022-05-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0010_prodcat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
